-- Midnight Delivery Supabase leaderboard setup
-- Run this in Supabase SQL Editor.

create table if not exists public.midnight_scores (
  id bigint generated by default as identity primary key,
  player_name text not null check (char_length(player_name) between 1 and 16),
  score integer not null check (score >= 0 and score <= 10000000),
  rank text not null,
  deliveries integer not null check (deliveries >= 0 and deliveries <= 10000),
  multiplier numeric(5,1) not null check (multiplier >= 1 and multiplier <= 999),
  near_misses integer not null check (near_misses >= 0 and near_misses <= 100000),
  created_at timestamptz not null default now()
);

create index if not exists midnight_scores_score_idx on public.midnight_scores (score desc);
create index if not exists midnight_scores_created_score_idx on public.midnight_scores (created_at desc, score desc);

alter table public.midnight_scores enable row level security;

drop policy if exists "Anyone can read leaderboard scores" on public.midnight_scores;
create policy "Anyone can read leaderboard scores"
on public.midnight_scores
for select
to anon
using (true);

drop policy if exists "Anyone can submit leaderboard scores" on public.midnight_scores;
create policy "Anyone can submit leaderboard scores"
on public.midnight_scores
for insert
to anon
with check (
  char_length(player_name) between 1 and 16
  and score >= 0 and score <= 10000000
  and deliveries >= 0 and deliveries <= 10000
  and multiplier >= 1 and multiplier <= 999
  and near_misses >= 0 and near_misses <= 100000
);
